default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 10

development:
  primary:
    <<: *default
    url: mysql2://root@localhost/projects_task_development
test:
  primary:
    <<: *default
    url: mysql2://root@localhost/projects_task_test

production:
  primary:
    <<: *default
    url: <%= ENV['MYSQL_DATABASE_URL'] %>
